name: Discord Bot

on:
  schedule:
    - cron: '0 10 * * *'
    - cron: '0 7 * * *'
  repository_dispatch:
    types:
      - sendAttendance
      - checkAttendance

jobs:
  sendAttendance:
    if: contains(github.event.schedule, '0 10')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python sendAskAttendance.py ${{ secrets.DISCORD_BOT_TOKEN }} ${{ secrets.DISCORD_CHANNEL_ID }} ${{ secrets.MESSAGE_GASURL }} ${{ secrets.MEMBERS_GASURL }}

  checkAttendance:
    if: contains(github.event.schedule, '0 7')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python checkAttendance.py ${{ secrets.DISCORD_BOT_TOKEN }} ${{ secrets.DISCORD_CHANNEL_ID }} ${{ secrets.MESSAGE_GASURL }} ${{ secrets.MEMBERS_GASURL }}
