name: Discord Bot

on:
  repository_dispatch

jobs:
  hello-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python main.py ${{ github.event.action }} ${{ secrets.DISCORD_BOT_TOKEN }} ${{ secrets.DISCORD_CHANNEL_ID }} ${{ secrets.MESSAGE_GASURL }} ${{ secrets.MEMBERS_GASURL}}